### ISSUE TITLE
Feature request: Toggle to switch snippets to be all caps

### ISSUE THREAD

**Issue by SNGoBoom** [dparkins/language-fortran#105]
Currently all of the snippets are in all lowercase.  I edited the snippets file to put all intrinsic functions in all uppercase to be compliant with the Fortran 90/95 standard.  I also changed the `print *,` statement with `WRITE (*,*)`.  A checkbox or toggle to switch between these two options in settings would be awesome.  The edited snippets file is attached.

[language-fortran.txt](https://github.com/dparkins/language-fortran/files/2199638/language-fortran.txt)

**Comment by dparkins** [comment]
The scope of the snippets matches to the file type and the grammar, and cannot be selected through a toggle or switch (it seems), as (I believe) the snippets package is looking for a unique file that matches the package (in this case fortran language) name. We could create a new grammar for these cases, but given what I understand about the snippets package, I don't think a toggle is possible at the moment.

**Comment by SNGoBoom** [comment]
That's a bummer.  Could that functionality be added by moving files around?  Like have a `storage` directory that has both files in it then just copying them into the `snippets` directory with an appropriate name change when the toggle is activated?  It wouldn't be elegant but it might work.

**Comment by dparkins** [comment]
That really doesn't sound very elegant, or indeed very secure! I would be very hesitant to add that, even if it could be done.
If you look in our README, we state:
> To access these additional grammars either select them manually via ctrl-shift-L or modify your init.coffee file to associate the desired grammar with the desired file extension as described here.

This looks like the best option to me, and snippets can change its behavior based on the grammar. So if there was a new grammar (called "Fortran 90/95 standard"), and you were to switch to that grammar using ctrl-shift-L, then the snippets should change accordingly.

**Comment by SNGoBoom** [comment]
Sounds good, thanks
