### ISSUE TITLE
The phrase "NB" is highlighted like an intrinsic when inside a comment

### ISSUE THREAD

**Issue by bcaddy** [dparkins/language-fortran#112]
My code has the phrase "NB" in a lot of the comments. This phrase is always highlighted like an intrinsic when it is inside the comments for some reason.  See attached screenshot 
<img width="672" alt="Screen Shot 2019-07-08 at 12 53 30" src="https://user-images.githubusercontent.com/41171425/60828011-69d50f00-a17f-11e9-99a1-d853df9c0f66.png">

**Comment by dparkins** [comment]
This isn't actually a feature of the '_language-fortran'_ community package, but rather a feature of the _'language-todo'_ core package (which also highlights other common commenting terms, such as FIXME, CHANGED, XXX etc). If this is a major issue for you, I suggest disabling _'language-todo_. If you need this package to be active for other reasons, and want a specific change for the _'language-fortran'_ package, please reopen this issue.

**Comment by bcaddy** [comment]
Ahh, that makes sense.  Sorry to waste your time.  Thanks!
