### ISSUE TITLE
Syntax highlighting stop working in the middle of he file.

### ISSUE THREAD

**Issue by MRedies** [dparkins/language-fortran#117]
If I open this file in atom: 
https://iffgit.fz-juelich.de/fleur/fleur/raw/47fcb5b934927f0641c4dc1f0a7ba57d3c76c79d/hybrid/kp_perturbation.F90 

The syntax highlighting will simply stop after line 263: 
![grafik](https://user-images.githubusercontent.com/6518935/72606049-2cb3bb80-391e-11ea-8508-34f1090e79a9.png)
I am note sure what is the cause, but if I delete lines 263&264 is works again.

**Comment by dparkins** [comment]
Unfortunately your variable name 'enum' is the ENUMERATOR type (from Fortran2003), similar to the C enum. So the highlighter is waiting for 'end enum' in your code.

**Comment by MRedies** [comment]
Ok. This seems to be the issue. I am ok with closing the issue. This seems to be a very specific case.
