### ISSUE TITLE
Variables names with "end" in them terminate the current block

### ISSUE THREAD

**Issue by elezar** [dparkins/language-fortran#20]
See the attached image, where the function block is prematurely terminated due the presence of a local variable ```an_end```.

Looking at the match rules in https://github.com/dparkins/language-fortran/blob/master/grammars/fortran%20-%20punchcard.cson, it would seem as if the end rule for the ```function-definition``` (and other blocks, ```program```, ```subroutine```, etc.) should include ```^\\s*``` before the capture of ```(end)```. For example:

```
      'end': '(?i)^\\s*(end)(?:\\s*(\\1)(\\s+\\2)?\\b)?\\s*([^;!\\n]+)?'
```

![image](https://cloud.githubusercontent.com/assets/931393/5696400/49d9df84-99d0-11e4-872c-eafa3088e1ca.png)

**Comment by elezar** [comment]
I have tested with Version 1.3.1, and the end in the middle of a block no longer causes the matching of the block to abort.

**Comment by elezar** [comment]
I have just seen that the following is also not highlighted correctly:
```
!=========================================================================================
! Return the indices of the local nodes that are in the specified global extents.

  function has_local_slice(this, global_extents)

    implicit none

! Parameters
    class(subgrid), intent(in) :: this
    integer, dimension(3,2), intent(in) :: global_extents
! Return value
    logical :: has_local_slice


    start_before_end = any(global_extents(:,1).le.this%node_extents(:,2))
    end_after_start = any(global_extents(:,2).ge.this%node_extents(:,1))

    has_local_slice = (start_before_end.and.end_after_start)

! Finished
    return

  end function has_local_slice
```

the "end" in the variable name ```end_after_start``` is taken as the end of the block.

**Comment by tomedunn** [comment]
@elezar I submitted a pull request containing a fix for this. It's a single line change so you can do the change yourself if you don't want to clone the branch. Thanks for posting the bug!
