### ISSUE TITLE
Comments not working in derived type definition constructs

### ISSUE THREAD

**Issue by tomedunn** [dparkins/language-fortran#32]
Just noticed that comments aren't working in derived type definition constructs. The fix for this is easy and I've already done/tested it on my local machine. I'll upload a fix tonight.

**Comment by michaelkonecny** [comment]
This doesn't seem to work for me.

In the following example, the comment isn't recognised:

```fortran
type shellres_str  ! results on shell elements
SEQUENCE
    real(8),dimension(8,4) :: fshell = 0d0 
    real(8),dimension(8,4) :: eps = 0d0
end type
```
