### ISSUE TITLE
Deprecation warning due to the use of scoped_properties instead of setings

### ISSUE THREAD

**Issue by elezar** [dparkins/language-fortran#34]
The Atom.io deprecation cop shows the following deprecation warning:

Store package settings files in the settings/ directory instead of scoped-properties/
Called 2 times:
```
Package.loadSettings - C:\Users\lezar\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:565:9
<unknown> - C:\Users\lezar\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:187:43
```

**Comment by ajclarke90** [comment]
Perhaps I'm being dense, but I'm still receiving this deprecation even though Atom thinks the package is up-to-date.

**Comment by elezar** [comment]
I don't think that the changes have been pushed out as an update yet. My package version is still at 1.4.0, which is from the 6th of March.

**Comment by dparkins** [comment]
This should now be resolved

**Comment by elezar** [comment]
I can confirm that the deprecation warning no longer shows on my system after the update to 1.5.0.
