### ISSUE TITLE
sub <TAB> inserting broken regex

### ISSUE THREAD

**Issue by jamesp** [dparkins/language-fortran#45]
I've just updated to the latest version of Atom.  Now using the fortran bundle when I type sub <TAB>:
![screen shot 2015-06-05 at 17 25 47](https://cloud.githubusercontent.com/assets/22805/8010419/f80a68f0-0ba7-11e5-9bc4-45f40fa017e0.png)

I get this autoinsert into the document:

![screen shot 2015-06-05 at 17 26 02](https://cloud.githubusercontent.com/assets/22805/8010436/0ff8d082-0ba8-11e5-904b-089d83bbb0cb.png)

**Comment by tomedunn** [comment]
Looks like something is wrong with the snippets. I haven't touched those since the initial port but I'll have a look to see if there is an easy fix. Does this happen with any of the other snippets?

**Comment by tomedunn** [comment]
OK, it looks like this is stuff left over after the original Textmate package was converted to work with Atom. The changes to fix this are easy enough. I should have a fix up sometime tonight.

**Comment by jamesp** [comment]
Fantastic, thanks Tom.  I took a look at the snippets file but haven't had any experience with writing Atom or Textmate packages so was struggling to find anything obvious (to me!).
