### ISSUE TITLE
Is it easy to set custom file extensions to be recognized as fortran? I have ftn, ftn90, cdk, thanks.

### ISSUE THREAD

**Issue by guziy** [dparkins/language-fortran#47]

**Comment by tomedunn** [comment]
You can set custom file extensions for any language in Atom by modifying your `init.coffee` file as discussed [here](https://discuss.atom.io/t/force-grammar-usage-for-file-extension/15154/6?u=tomedunn). For your case try

```coffee
path = require 'path'

atom.workspace.observeTextEditors (editor) ->
    if path.extname(editor.getPath()) in [".ftn", ".ftn90", ".cdk"]
        editor.setGrammar(atom.grammars.grammarForScopeName('source.fortran.modern'))
```

**Comment by guziy** [comment]
Thank you very much Tom:

It works very nicely.

Cheers
