### ISSUE TITLE
A line starting with (!) is not recognized as a comment in .f files

### ISSUE THREAD

**Issue by guziy** [dparkins/language-fortran#49]
Hi:

Here is the example code

```
      program test
!this is a comment
c no this is a comment
        print *, 'Hello' 
      end
```

And here is how it looks in the editor:

![screen shot 2015-07-27 at 10 44 51](https://cloud.githubusercontent.com/assets/900941/8908900/944a3052-344c-11e5-9211-cb24842607fd.png)

Is it possible to configure this to treat (!) - as a comment start in .f files as well?

Cheers

**Comment by tomedunn** [comment]
The grammar is treating the `.f` file as adhering to a different Fortran standard, the Fortran 1977 standard to be exact. You should be able to force Atom to apply the "modern" Fortran grammar to `.f` files by modifying your `init.coffee` file as discussed [here](https://discuss.atom.io/t/force-grammar-usage-for-file-extension/15154/6?u=tomedunn). For your case try

```coffee
path = require 'path'

atom.workspace.observeTextEditors (editor) ->
    if path.extname(editor.getPath()) in [".f"]
        editor.setGrammar(atom.grammars.grammarForScopeName('source.fortran.modern'))

**Comment by guziy** [comment]
Thanks Tom:

It works very nicely.

Cheers
