### ISSUE TITLE
"!" does not highlight the line as a comment

### ISSUE THREAD

**Issue by anup-boisestate** [dparkins/language-fortran#50]
Using an exclamation (!) character to comment code does not highlight the code as comment

**Comment by tomedunn** [comment]
Are you working in a `.f` or `.f90` file? `.f` files use the `punchcard - fortran` grammar which follows the 1977 standard and doesn't include `!` as a comment character.

**Comment by anup-boisestate** [comment]
I am working with a `.f` file. Thank you for the quick response.

**Comment by tomedunn** [comment]
Glad I could help! Since you're not the first person who's asked for this I'll make a note to update  `README.md` to explain this.
