### ISSUE TITLE
color of procedures in types that share name with intrinsic function

### ISSUE THREAD

**Issue by maxlevesque** [dparkins/language-fortran#54]
Hi there,

When one writes procedures in types, and when this procedure has the name of an intrinsic function, coloration is wrong. See example below:

![screenshot from 2015-09-02 16 41 34](https://cloud.githubusercontent.com/assets/1818339/9634387/c0710d56-5191-11e5-93bc-3043958af9b2.png)

log should be white.

It seems to me that any word preceded by `%` should be considered as non-intrinsic.

Best wishes,

**Comment by tomedunn** [comment]
I'm pretty sure I can modify either the intrinsic function definition or the variable definition to not mark functions following `%` as being intrinsic. I'll see what I can do tonight.

**Comment by maxlevesque** [comment]
This seems to be not only true for intrinsic procedures (see log example above), but also for kinds, like real, int, etc.


![screenshot from 2015-09-02 17 19 21](https://cloud.githubusercontent.com/assets/1818339/9635483/f73e532a-5196-11e5-8cae-9390b6806463.png)

**Comment by maxlevesque** [comment]
Thanks @tomedunn  :).


![screenshot from 2015-09-28 12 18 09](https://cloud.githubusercontent.com/assets/1818339/10133083/01cf936e-65db-11e5-8213-ce0974e7fd6b.png)

**Comment by tomedunn** [comment]
No problem @maxlevesque. If you're feeling adventurous be sure to try the new `Fortran - Free Form` grammar. In principle it should work almost identically to the `Fortran - Modern` grammar with some minor differences. It highlights all of my static test programs perfectly but sometimes bugs only pop up when actively typing.
