### ISSUE TITLE
c in first column: problem with close() intrinsic in free format

### ISSUE THREAD

**Issue by maxlevesque** [dparkins/language-fortran#55]
Hi,
Good example being better than long sentences:
![screenshot from 2015-09-02 18 08 01](https://cloud.githubusercontent.com/assets/1818339/9636783/96d68438-519d-11e5-90a8-2c6d2f9d4977.png)

Source file has extension .f90

Also affects other intrinsics starting with c and likely to appear in first column of the file, like `character`

Might be related to recent issue https://github.com/dparkins/language-fortran/issues/52

**Comment by tomedunn** [comment]
From checking the latest standard, `c` or `C` in the first character slot should only count as a comment in fixed formatted Fortran. So only the sections beginning with a `!` should be commented in your examples. This change is easy enough to make. I'll be sure to do so when I get home tonight.

**Comment by tomedunn** [comment]
I added a fix to this in my fork tomedunn/language-fortran however I'm going to hold off on a pull request until the end of the weekend. I know there are some people who use the Modern Fortran grammar for fixed formed Fortran. I'd like to break the two grammars, Punchcard Fortran and Modern Fortran into Free Form Fortran and Fixed Form Fortran. That way both can work with the current standard.
