### ISSUE TITLE
& in derived type declarations

### ISSUE THREAD

**Issue by maxlevesque** [dparkins/language-fortran#62]
That's not an important issue, but since I came across... here it is.
`&` character in first place of a declaration inside a type declaration seems to mess it up:
 
![screenshot from 2015-10-20 17 38 34](https://cloud.githubusercontent.com/assets/1818339/10612546/9c564072-7751-11e5-850a-1c840dd193c1.png)

**Comment by tomedunn** [comment]
Thanks for posting @maxlevesque. I'll look into this tonight if I get a chance. It should be a pretty simple fix.
