### ISSUE TITLE
variable attributes being skipped

### ISSUE THREAD

**Issue by tomedunn** [dparkins/language-fortran#67]
For some reason attributes in type definition statements are being arbitrarily skipped in some cases as shown below
![image](https://cloud.githubusercontent.com/assets/5925666/10952497/b35a3216-8308-11e5-9c81-80cff908483e.png)
This bug was not present in earlier versions of Atom and I believe it's a bug in [first-mate](https://github.com/atom/first-mate) possibly related to [this issue](https://github.com/atom/first-mate/issues/62). I'll see what I can do about fixing this but we may have to wait for a newer release of Atom to fix it.

**Comment by maxlevesque** [comment]
thanks tom ! :)
