### ISSUE TITLE
`type` variable confuse syntax highlighting

### ISSUE THREAD

**Issue by Luthaf** [dparkins/language-fortran#70]
A variable called type confused syntax highlighting when assigned from a fucntion call, but not when assign from a literal.
![syntax highlighting error](https://cloud.githubusercontent.com/assets/6141587/11242852/b5c75dc4-8e04-11e5-8425-636ed3804979.png)

(I discovered with this that `type` is not a reserved word. Fortran parsing must be so hard ...)

**Comment by tomedunn** [comment]
Nice catch and thanks for posting!

**Comment by Luthaf** [comment]
Wow, that is reactivity! Thank you!
