### ISSUE TITLE
Highlights FORALL statements as errors

### ISSUE THREAD

**Issue by chris-revell** [dparkins/language-fortran#90]
![screen shot 2016-12-02 at 12 13 29](https://cloud.githubusercontent.com/assets/17123390/20833675/c33f3ab2-b888-11e6-84bf-f327def33b75.png)

**Comment by tomedunn** [comment]
Thanks for posting this!

I'll try to modify the rules to allow for `forall` statements later today. It should be possible given I was able to do the same thing for `if` statements.

**Comment by chris-revell** [comment]
Great. I'd do it myself but have no experience changing syntax packages.

**Comment by tomedunn** [comment]
From experience, implementing this particular fix would be a really difficult one to tackle as your first try at modifying this syntax package. Thankfully the trick to making it work is already implemented in the rules for the `where` statement and construct. So it should just be a matter of copying the rules for that and modifying them to work for `forall` instead.

**Comment by chris-revell** [comment]
Great work fixing that so quickly. I'll wait for the update to come through Atom.
