### ISSUE TITLE
Highlights unformatted write statements as errors

### ISSUE THREAD

**Issue by chris-revell** [dparkins/language-fortran#92]
![screen shot 2017-01-03 at 09 36 35](https://cloud.githubusercontent.com/assets/17123390/21604197/b5dbf69c-d199-11e6-9aae-03f7a60180d8.png)

**Comment by tomedunn** [comment]
Thanks for posting! I was able to recreate the error. The problem has to do with the `real(time)` statement which is being interpreted as a type declaration rather than a function. This should be easily fixable.

**Comment by chris-revell** [comment]
You're right, I've removed the `real()` and it no longer complains. That `real()` call was an artefact that didn't need to be there anyway, but at least it highlighted a problem. 
Keep up the good work!
