### ISSUE TITLE
Rewind not highlighted.

### ISSUE THREAD

**Issue by SolidTux** [dparkins/language-fortran#97]
Like the title says, the rewind keyword is not highlighted.

**Comment by tomedunn** [comment]
Would you mind posting a screen shot of what you are describing? The rewind statement appears to be working find for me.
![image](https://user-images.githubusercontent.com/5925666/29369704-fe9fd008-8268-11e7-9d0b-66efb7f9b86b.png)
Also, what color theme are you using? Do `read` and `write` statements highlight correctly for you?

**Comment by tomedunn** [comment]
OK, I think I might know what you're referring to. `rewind` along with several other IO-statements don't work without brackets. This should be an easy fix. I'll try to post an update later today.

**Comment by SolidTux** [comment]
Thank you for your very fast answer and even solution!
